environment:
  size: 10
  resolution: 1
  min_num_signal_points: 5
  max_num_signal_points: 30
  min_num_obstacles: 5
  max_num_obstacles: 20
  signal_weight: 1.0
  obstacle_weight: 1.0
  obstacle_penalty: -1.0
  perception_range: 2
  distance_attenuation_factor: 1

drone:
  max_collect_range: 1
  battery: 128
  max_speed: 1

training:
  use_mcts: False
  use_mcts_to_train: False
  checkpoint_interval: 10
  gamma: 0.99
  lambda_gae: 0.95  # GAE参数，一般介于0.9到0.99之间
  entropy_coef: 0.01  # 熵正则化系数，一般介于0.01到0.1之间
  batch_size: 128
  epochs: 1000
  lr: 0.00001  # 学习率
  BATCH_SIZE: 128
  max_buffer: 10000

penalties_rewards:
  invalid_action_penalty: -10
  collision_penalty: -100
  target_reward: 100
  default_penalty: 1
  collect_info_cost: 1

datasets:
  global_flow:
    data_file: "data/processed/all_global_data.json"
    model_path: "saved_models/global_flow/global_flow_model_val_loss0.6729.pt"
  local_flow:
    data_dir: "data/processed/all_local_data.json"
    model_path: "saved_models/local_flow/local_flow_model_val_loss4.9445.pt"
  mcts:
    data_dir: "data/raw/all_state-value-pair_data.json"
    model_path: "saved_models/mcts_vnet/mcts_vnet_episode0_step0_loss1.842281699180603.pt"
    save_model_path: "saved_models/mcts_vnet/"

models:
  global_flow_model:
    hidden_dim: 128
    transformer_heads: 8
    transformer_layers: 4
    dropout: 0.1
    environment_size: 10
  local_flow_model:
    model_dim: 1024
    num_heads: 8
    num_encoder_layers: 3
    num_decoder_layers: 3
    feedforward_dim: 2048
    dropout: 0.1
    perception_range: 2
  mcts_vnet_model:
    input_dim: 10
    hidden_layers: [20, 20, 20]
    dropout: 0.5
    available_actions: 9
    perception_range: 2
    environment_size: 10
